"use client";

import React, { useEffect, useState } from "react";
import { GridColDef, GridRenderCellParams } from "@mui/x-data-grid";
import GenericCrudTable from "@/components/adminComponents/tables/GenericCrudTable";
import FeedbackForm from "@/components/adminComponents/forms/FeedbackForm";
import { Feedback, FeedbackStatus } from "@/configs/dataTypes"; // Assumed import
import { API_BASE_URL } from "@/configs/constants";

// Interface for fetching related IDs, similar to Customer
interface Customer {
  id: string;
  firebase_UID: string;
}

export default function FeedbackPage() {
  const apiUrl = `${API_BASE_URL}/Feedbacks`;
  const [customerMap, setCustomerMap] = useState<Record<string, string>>({});

  // Fetch Customer map for display
  useEffect(() => {
    const fetchCustomers = async () => {
      try {
        const custRes = await fetch(`${API_BASE_URL}/Customers`);
        const custJson = await custRes.json();
        const customers: Customer[] = Array.isArray(custJson)
          ? custJson
          : custJson.data || [];

        const cMap: Record<string, string> = {};
        customers.forEach((c) => {
          if (c.id) cMap[c.id] = c.firebase_UID || "Unknown";
        });
        setCustomerMap(cMap);
      } catch (err) {
        console.error("Failed to fetch customer mappings", err);
      }
    };
    fetchCustomers();
  }, []);

  const columns: GridColDef<Feedback>[] = [
    {
      field: "firebase_UID",
      headerName: "Customer (UID)",
      flex: 1.2,
      minWidth: 180,
      renderCell: (params: GridRenderCellParams<Feedback, string | null>) =>
        params.value || "Anonymous",
    },
    {
      field: "subject",
      headerName: "Subject",
      flex: 1,
      minWidth: 150,
      renderCell: (params) => params.value || "N/A",
    },

    {
      field: "message",
      headerName: "Message Preview",
      flex: 2,
      minWidth: 250,
      // Truncate message for table view
      renderCell: (params: GridRenderCellParams<Feedback, string | null>) => {
        const message = params.value || "";
        return message.length > 80
          ? message.substring(0, 77) + "..."
          : message || "—";
      },
    },
    {
      field: "rating",
      headerName: "Rating",
      flex: 0.5,
      minWidth: 100,
      align: "left",
      type: "number",
      renderCell: (params) => {
        const rating = Number(params.value);
        if (!rating || rating <= 0) return "N/A";
        return "⭐️".repeat(Math.min(rating, 5)); // limits to max 5 stars for display
      },
    },
    {
      field: "submittedAt",
      headerName: "Submitted on",
      flex: 0.8,
      minWidth: 180,
      renderCell: (params: GridRenderCellParams<Feedback, string>) => {
        if (!params.value) return "";
        const dateObj = new Date(params.value);

        // Date part: DD-MM-YYYY
        const day = String(dateObj.getDate()).padStart(2, "0");
        const month = String(dateObj.getMonth() + 1).padStart(2, "0");
        const year = dateObj.getFullYear();
        const datePart = `${day}-${month}-${year}`;

        // Time part: HH:MM AM/PM (12-hour format)
        let hours = dateObj.getHours();
        const minutes = String(dateObj.getMinutes()).padStart(2, "0");
        const ampm = hours >= 12 ? "PM" : "AM";
        hours = hours % 12;
        hours = hours ? hours : 12; // the hour '0' should be '12'
        const hour12 = String(hours).padStart(2, "0");

        const timePart = `${hour12}:${minutes} ${ampm}`;

        return `${datePart} ${timePart}`;
      },
    },
    {
      field: "status",
      headerName: "Status",
      flex: 0.6,
      minWidth: 120,
    },
  ];

  // Based on CreateFeedbackDto and sample data
  const initialFeedback: Feedback = {
    id: "", // Will be generated by the API
    firebase_UID: null,
    subject: null,
    message: null,
    rating: null,
    status: FeedbackStatus.New,
    submittedAt: new Date().toISOString(), // Use current time
  };

  return (
    <GenericCrudTable<Feedback>
      title="Feedback"
      apiUrl={apiUrl}
      columns={columns}
      initialFormData={initialFeedback}
      renderForm={(data, setData) => (
        <FeedbackForm data={data} setData={setData} customerMap={customerMap} />
      )}
    />
  );
}
