"use client";

import React from "react";
import { GridColDef, GridRenderCellParams } from "@mui/x-data-grid";
import GenericCrudTable from "@/components/adminComponents/tables/GenericCrudTable";
import EnquiryForm from "@/components/adminComponents/forms/EnquiryForm";
import { Enquiry, EnquiryStatus } from "@/configs/dataTypes"; // Assumed import
import { API_BASE_URL } from "@/configs/constants";

export default function EnquiriesPage() {
  const apiUrl = `${API_BASE_URL}/Enquiries`;

  const columns: GridColDef<Enquiry>[] = [
    {
      field: "fullName",
      headerName: "Full Name",
      flex: 1,
      minWidth: 150,
    },

    {
      field: "email",
      headerName: "Email",
      flex: 1.5,
      minWidth: 200,
    },
    {
      field: "phoneNumber",
      headerName: "Phone",
      flex: 0.7,
      minWidth: 120,
    },
    {
      field: "message",
      headerName: "Message Preview",
      flex: 2,
      minWidth: 250,
      // Truncate message for table view
      renderCell: (params: GridRenderCellParams<Enquiry, string>) => {
        const message = params.value || "";
        return message.length > 80 ? message.substring(0, 77) + "..." : message;
      },
    },
    {
      field: "submittedAt",
      headerName: "Submitted on", // Updated header name
      flex: 0.8, // Increased flex for space
      minWidth: 180, // Increased minWidth
      renderCell: (params: GridRenderCellParams<Enquiry, string>) => {
        if (!params.value) return "";
        const dateObj = new Date(params.value);

        // Date part: DD-MM-YYYY
        const day = String(dateObj.getDate()).padStart(2, "0");
        const month = String(dateObj.getMonth() + 1).padStart(2, "0");
        const year = dateObj.getFullYear();
        const datePart = `${day}-${month}-${year}`;

        // Time part: HH:MM AM/PM (12-hour format)
        let hours = dateObj.getHours();
        const minutes = String(dateObj.getMinutes()).padStart(2, "0");
        const ampm = hours >= 12 ? "PM" : "AM";
        hours = hours % 12;
        hours = hours ? hours : 12; // the hour '0' should be '12'
        const hour12 = String(hours).padStart(2, "0");

        const timePart = `${hour12}:${minutes} ${ampm}`;

        return `${datePart} ${timePart}`;
      },
    },
    {
      field: "status",
      headerName: "Status",
      flex: 0.6,
      minWidth: 120,
    },
  ];

  // Based on CreateEnquiryDto and sample data
  const initialEnquiry: Enquiry = {
    id: "", // Will be generated by the API
    fullName: "",
    email: "",
    phoneNumber: "",
    message: "",
    status: EnquiryStatus.New,
    submittedAt: new Date().toISOString(), // Use current time
  };

  return (
    <GenericCrudTable<Enquiry>
      title="Enquiries"
      apiUrl={apiUrl}
      columns={columns}
      initialFormData={initialEnquiry}
      renderForm={(data, setData) => (
        <EnquiryForm data={data} setData={setData} />
      )}
    />
  );
}
